### ISSUE TITLE
Item desync

### ISSUE THREAD

**Issue by Restioson** [NucleoidMC/plasmid#5]
Shows up in colour swap, loop de loop, and spleef.

**Comment by gegy1000** [comment]
This has potentially been fixed in 0.3, but need to do more extensive testing to confirm

**Comment by Restioson** [comment]
Epic

**Comment by redcreeper14385** [comment]
Can still occur from time to time in Mineout, particularly on the Elytra section.
Can also be present some of the time in Quakecraft, and I have experienced it a few times in Micro Battle although that seems to be fixed these days.

**Comment by SimplyCmd** [comment]
From my findings it shows up in nearly every game, including the lobby 😬

**Comment by Gegy** [comment]
This has been resolved! 🎉
